INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(100.00, 'Categoria1', 'Produto 1');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(100.00, 'Categoria2', 'Produto 2');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(100.00, 'Categoria3', 'Produto 3');